config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show] do
    member { get :delete }
  end
  resources :reviews, except: :destroy do
    member { get :delete }
  end
  resources :movies, only: [:index, :new, :create]

  put '/movie/:id/like', to: 'movies#like', as: 'like'
  put '/movie/:id/unlike', to: 'movies#unlike', as: 'unlike'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "welcome#home"

  get '/login', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create', as: 'new_session'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  get '/movies/select', to: 'movies#select', as: 'select_movie'
  get '/movies/:id', to: 'movies#show', as: 'movie'
  delete '/reviews/:id', to: 'reviews#destroy', as: 'destroy_review'
  get '/reviewed-movies', to: 'movies#reviewed', as: 'reviewed_movies'

  delete '/users/:id', to: 'users#destroy', as: 'destroy_user'

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def select 
  end

  def reviewed
    @movies = Review.all.map { |review| review.movie }.uniq
  end
  
  def index
    if !params[:movie_title].empty?
      @movies = Movie.get_movies(params[:movie_title])
    else
      flash[:notice] = "Enter a movie title."
      render :select
    end
  end

  def show
    @movie = Movie.find_by(id: params[:id])
    @reviews = @movie.reviews
    @user = User.find_by(id: session[:user_id])
  end

  def like 
    #grabbing the review
    @movie = Movie.all.find(params[:id])
    #creating a like with that post and the current users id
    Like.create(user_id: session[:user_id], movie_id: @movie.id)
    #redirecting them back to that post
    redirect_to movie_path(@movie)
  end

  def unlike
    @movie = Movie.find_by(id: params[:id])
    @like = Like.find_by(user_id: session[:user_id], movie_id: @movie.id)
    @like.destroy
    redirect_to movie_path(@movie)
  end

  def new
    movie_params = Movie.get_movie_details(params[:movie][:imdb_id])
    if !Movie.find_by(imdbid: params[:movie][:imdb_id])
      @movie = Movie.new(movie_params)
      @movie.save
    else
      @movie = Movie.find_by(imdbid: params[:movie][:imdb_id])
    end
    session[:movie_id] = @movie.id
    redirect_to new_review_path
  end

  def create 
  end
    
  def update
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/index.html.erb
<style>
  body {
    background-image: url(https://hollywoodtheatre.org/media/images/Repressed_Cinema.original.height-720.width-1280.jpg);
  }
  div {
    text-align: center;
  }
  .words {
    color: white;
    font-size: 25px;
  }
</style>

<% @movies.each do |movie| %>

  <div><%= image_tag movie["Poster"]  if movie["Poster"] != "N/A"%></div>
  <p class="words"><%= movie["Title"]  %></p>
  <p class="words"><%= movie["Year"] %></p>
  <p><%= link_to "Review This Movie", new_movie_path(:movie => {:imdb_id => movie["imdbID"]}) %></p>
<% end %>

app/views/movies/reviewed.html.erb
<style>
  div {
    text-align: center;
  }
</style>


<h1>Reviewed Movies</h1>

<% @movies.each do |movie| %>
  <div><%= link_to image_tag(movie.poster), movie_path(movie) %></div>
<%end%>

app/views/movies/select.html.erb
<style>
  form {
    text-align: center;
  }
  p {
    color: rgb(211, 41, 41);
    font-size: 20px;
    padding: 20px;
  }
</style>

<h1>Enter Movie Title</h1>

<% if flash[:notice] %>
  <p><strong><%= flash[:notice] %><strong></p>
<%end%>

<%= form_tag(movies_path, method: 'get') do %>
  <%= text_field_tag :movie_title, nil, placeholder: 'Enter Title' %>
  <%= submit_tag "Show Movies" %>
<% end %>

app/views/movies/show.html.erb
<style>
  body {
    background-image: url(https://png.pngtree.com/thumb_back/fw800/back_pic/02/66/87/73578b94f836a03.jpg);
  }
  div {
    text-align: center;
  }
  h3 {
    color: rgb(211, 41, 41);
    font-size: 30px;
  }
  p {
    color: white;
    font-size: 20px;
  }
  #reviews {
    border: 4px solid rgb(211, 41, 41);
  }
  h2 {
    text-align: center;
    color: rgb(211, 41, 41);
    font-size: 38px;
  }
  .user_reviews {
    text-align: center;
    color: white;
  }
  #user_reviews_username {
    font-size: 22px;
    text-decoration: underline;
  }
  #user_reviews_content {
    font-size: 22px;
  }
</style>
<h1><%= @movie.title %></h1>
<div><%= image_tag @movie.poster %></div>


<div id="likes"> 
  <h3>Likes:</h3> 
  <p><%= @movie.like_count %></p>
</div>

<div>
  <% if @movie.liked?(@user)%>
    <a><%= button_to  "Unlike", unlike_path(@movie), method: "put" %></a>
  <%else%>
    <a><%= button_to  "Like", like_path(@movie), method: "put" %></a>
  <% end %>
</div>



<div>
  <h3>Rating</h3>
  <p><%= @movie.rated %></p>
</div>

<div>
  <h3>Released</h3>
  <p><%= @movie.released %></p>
</div>

<div>
  <h3>Runtime</h3>
  <p><%= @movie.runtime %></p>
</div>

<div>
  <h3>Genre(s)</h3>
  <p><%= @movie.genre %></p>
</div>

<div>
  <h3>Director</h3>
  <p><%= @movie.director %></p>
</div>

<div>
  <h3>Actors</h3>
  <p><%= @movie.actors %></p>
</div>

<div>
  <h3>Plot</h3>
  <p><%= @movie.plot %></p>
</div>

<div>
  <h3>Studio</h3>
  <p><%= @movie.production %></p>
</div>


<div id="reviews">
  <h2>Reviews</h2>
    <% @reviews.each do |review| %>
      <div style="border: 2px solid white">
        <div class="user_reviews" id="user_reviews_username"><strong>@<%= review.user.username %></strong></div>
        <div class="user_reviews" id="user_reviews_content"><%= review.content %></div>
      </div>
    <%end%>
</div>