config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show] do
    member { get :delete }
  end
  resources :reviews, except: :destroy do
    member { get :delete }
  end
  resources :movies, only: [:index, :new, :create]

  put '/movie/:id/like', to: 'movies#like', as: 'like'
  put '/movie/:id/unlike', to: 'movies#unlike', as: 'unlike'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "welcome#home"

  get '/login', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create', as: 'new_session'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  get '/movies/select', to: 'movies#select', as: 'select_movie'
  get '/movies/:id', to: 'movies#show', as: 'movie'
  delete '/reviews/:id', to: 'reviews#destroy', as: 'destroy_review'
  get '/reviewed-movies', to: 'movies#reviewed', as: 'reviewed_movies'

  delete '/users/:id', to: 'users#destroy', as: 'destroy_user'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
    if session[:user_id]
      session[:logged_in] = true
      @user = User.find_by(id: session[:user_id])
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/home.html.erb
<% if flash[:notice] %>
  <p id="logged_out_notice"><%= flash[:notice] %></p>
<%end%>
<% if flash[:destroyed_user] %>
  <p id="destroyed_user_notice"><%= flash[:destroyed_user] %></p>
<%end%>

<% if @user %>
  <h1>Welcome to The Movie Reviewer, <%="#{@user.first_name}"%>!</h1>
  <div>
    <p style="text-align: left; vertical-align: top"><%= link_to "Logout", logout_path %></p>
    <p style="text-align: left; vertical-align: top"><%= link_to "Deactivate", [:delete, @user] %></p>
    <p><%= link_to "All Reviewed Movies", reviewed_movies_path %></p>
    <p><%= link_to "My Reviews", reviews_path %></p>
    <p><%= link_to "Review a Movie", select_movie_path %></p>
  </div>
<% else %>
  <h1>Welcome to The Movie Reviewer</h1>
<%end%>