config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show] do
    member { get :delete }
  end
  resources :reviews, except: :destroy do
    member { get :delete }
  end
  resources :movies, only: [:index, :new, :create]

  put '/movie/:id/like', to: 'movies#like', as: 'like'
  put '/movie/:id/unlike', to: 'movies#unlike', as: 'unlike'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "welcome#home"

  get '/login', to: 'sessions#new', as: 'login'
  post '/sessions', to: 'sessions#create', as: 'new_session'
  get '/logout', to: 'sessions#destroy', as: 'logout'

  get '/movies/select', to: 'movies#select', as: 'select_movie'
  get '/movies/:id', to: 'movies#show', as: 'movie'
  delete '/reviews/:id', to: 'reviews#destroy', as: 'destroy_review'
  get '/reviewed-movies', to: 'movies#reviewed', as: 'reviewed_movies'

  delete '/users/:id', to: 'users#destroy', as: 'destroy_user'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  # before_action :authenticate_user, only: [:like]
  # before_action :set_post, only: [:show, :like]


  def index
    @user = User.find_by(id: session[:user_id])
    @reviews = @user.reviews
  end

  def show
    @review = Review.find_by(id: params[:id])
    @user = User.find_by(id: session[:user_id])
  end

  def new      
    @movie = Movie.find_by(id: session[:movie_id])
    @review = Review.new
  end

  def create 
    @movie = Movie.find_by(id: session[:movie_id])
    @review = Review.new(review_params)
    if @review.save
      redirect_to review_path(@review)
    else
      flash[:errors] = @review.errors.full_messages
      render :new
    end
  end

  def edit
    @review = Review.find_by(id: params[:id])
  end
    
  def update
    @review = Review.find_by(id: params[:id])
    @review.update(review_params)
    redirect_to review_path(@review)
  end

  # def like 
  #   if !current_user.liked? @review
  #     @review.liked_by current_user
  #   elsif current_user.liked? @review
  #     @review.unliked_by current_user
  # end

  def delete
    @review = Review.find_by(id: params[:id])
  end

  def destroy
    @review = Review.find_by(id: params[:id])
    @review.destroy 
    redirect_to reviews_path
  end

  private

  def review_params
    x = params.require(:review).permit(:content)
    if !(params[:action] == 'update')
      x[:user_id] = session[:user_id]
      x[:movie_id] = session[:movie_id]
    end
    x
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/delete.html.erb
<style>
  h2 {
    text-align: center;
    color: rgb(211, 41, 41);
  }
  div {
    text-align: center;
  }
</style>
<div>
  <%= form_for @review, html: {method: :delete} do |f| %>
    <h2>Are you sure you want to delete this review?</h2>
    <a><%= f.submit "Delete" %></a>  <%= link_to "Cancel", reviews_path %>
  <%end%>
</div>

app/views/reviews/edit.html.erb
<style>
  div {
    text-align: center;
  }
</style>

<h1>Edit Review for <%= @review.movie.title %></h1>

<% if flash[:errors] %>
  <% flash[:errors].each do |msg| %>
    <p style="color:red"> <%= msg %> </p>
  <%end%>
<%end%>

<div>
  <%= form_for @review do |f| %>
    <p>Content: <%= f.text_area :content %><br></p>
    <%= f.submit %>
  <%end%>
</div>

app/views/reviews/index.html.erb
<style>
body {
  background-image: url(https://hollywoodtheatre.org/media/images/Repressed_Cinema.original.height-720.width-1280.jpg);
}
span {
  color: white;
  font-size: 20px;
  border: 2px solid white;
  box-sizing: content-box;
  padding: 5px;
}
img {
  display: block;
  margin-left: auto;
  margin-right: auto;
  width: 15%;
}
h3 {
  text-align: center;
}
div {
  text-align: center;
}

</style>
<h1>My Reviews</h1>

<% @reviews.each do |review| %>
  <%= image_tag review.movie.poster %>
  <h3><%= link_to review.movie.title, movie_path(review.movie) %></h3>
  <div><span><%= review.content %></span></div>
  <div>
    <%= link_to "View", review_path(review) %>
    <%= link_to "Edit", edit_review_path(review), method: :get %>
    <%= link_to "Delete", [:delete, review] %>
  </div>
  <h4>---------------------------------------------------------</h4>
<%end%> 

app/views/reviews/new.html.erb
<style>
  form {
    text-align: center;
  }
</style>

<h1>New Review for <%= @movie.title %></h1>

<% if flash[:errors] %>
  <% flash[:errors].each do |msg| %>
    <p style="color:red"><strong> <%= msg %> </strong></p>
  <%end%>
<%end%>

<%= form_for @review do |f| %>
  Content: <%= f.text_area :content %><br>
  <%= f.submit %>
<%end%>

app/views/reviews/show.html.erb
<h1><%= link_to @review.movie.title, movie_path(@review.movie) %></h1>
<%= image_tag @review.movie.poster %>

<div>
  <h2>Your Review</h2>
  <p><%= @review.content %></p>
</div>

<p><%= link_to "Edit", edit_review_path(@review) %></p>